kind: Service
apiVersion: v1
metadata:
  name: {{ index .Values "alertmanager-msteams" "name" }}-service
spec:
  selector:
    app: {{ index .Values ""alertmanager-msteams" "template" "metadata" "labels" "app" }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10010